### ISSUE TITLE
cannot add Limit when query Dynamo in queryItems() dck-lambda-utils

### ISSUE THREAD

**Issue by andyliu-417** [AgileVisionCompany/dck#45]
`export interface IQueryOptions {
  page?: number;
  limit?: number;
  query?: any;
  data?: any;
  comparisonOperators?: any;
}`

limit does not exist inside the queryItems function.

**Comment by py3ir** [comment]
@andyliu-417 Can you give a more description of your problem?
Are you about [this](https://github.com/AgileVisionCompany/dck/blob/8fe466361291c0db66f16c249e175e9b77a941be/packages/dck-lambda-utils/src/DynamoDbDataSource.ts#L40) function which used limit parameter [here](https://github.com/AgileVisionCompany/dck/blob/8fe466361291c0db66f16c249e175e9b77a941be/packages/dck-lambda-utils/src/DynamoDbDataSource.ts#L92)?

**Comment by ambroseus** [comment]
current version of dck-lambda-utils is no longer supported
